#!/bin/bash

profile="프로필이름"  ##프로필 이름을 적어줍니다
output_file="iam_users_log.csv"  ## 출력할 파일 이름을 변경하고 싶으면 여기서 변경할 수 있습니다.
echo "No,AccountNumber,UsersName,UserID,CreateDate,PasswordLastUsed,Groups" > $output_file

# 계정 번호 한 번만 가져오기
account_id=$(aws sts get-caller-identity --profile "$profile" --query Account --output text)

# 사용자 이름 목록 가져오기기
users=$(aws iam list-users --profile "$profile" --query 'Users[*].UserName' --output text)

i=1
for user in $users; do
	username="$user"
	userid=$(aws iam get-user --profile "$profile" --user-name "$user" --query 'User.UserId' --output text 2>/dev/null)
	created=$(aws iam get-user --profile "$profile" --user-name "$user" --query 'User.CreateDate' --output text 2>/dev/null)
	[[ "$created" == "None" || "$created" == "null" ]] && created=""
	[[ -n $created ]] && created=${created%%+*}	
	last_used=$(aws iam get-user --profile "$profile" --user-name "$user" --query 'User.PasswordLastUsed' --output text 2>/dev/null)
	[[ "$last_used" == "None" || "$last_used" == "null" ]] && last_used=""
	[[ -n $last_used ]] && last_used=${last_used%%+*}



# 그룹 목록 가져오기
	groups=$(aws iam list-groups-for-user --profile "$profile" --user-name "$user" --query 'Groups[].GroupName' --output text 2>/dev/null)
	[[ -z "$groups" ]] && groups="-"

	echo "$i,'$account_id',$username,$userid,$created,$last_used,$groups" >> "$output_file"
	((i++))
done

echo "made $output_file"
